### Register
POST https://localhost:7123/api/auth/register
Content-Type: application/json

{
  "firstName": "Fidelity",
  "lastName": "Agboji",
  "email": "fidelity@test.com",
  "password": "Password123!"
}

### Login
POST https://localhost:7123/api/auth/login
Content-Type: application/json

{
  "email": "fidelity@test.com",
  "password": "Password123!"
}

### Access secured endpoint
GET https://localhost:7123/api/secured
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

### Access admin-only endpoint
GET https://localhost:7123/api/secured/admin
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

### Refresh token
POST https://localhost:7123/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}